Feature/create migration
s21platform/notification-service pull request #6
Opened 2024-08-09 15:21 UTC by vladimirfrolovv

2024-08-09 15:22 UTC, vladimirfrolovv commented
Create migrations, test data, copy docker file and scripts

2024-08-10 12:10 UTC, alexseipopov requested changes

2024-08-10 12:10 UTC, alexseipopov commented on for_test/docker-compose.yml
> +version: '3.9'
Воваааа!! как это пробралось?))))

2024-08-10 12:10 UTC, alexseipopov commented on for_test/test_data.sql
> +INSERT INTO notifications (user_id, notification, readed, created_time, readed_time)
тот же вопрос, что и к компоузу

2024-08-10 15:14 UTC, vladimirfrolovv commented on for_test/docker-compose.yml
> +version: '3.9'
Я просто подумал, чтобы Маше тестить тоже можно было , или это кринж и лучше убрать ?

2024-08-10 15:14 UTC, vladimirfrolovv commented on for_test/docker-compose.yml
> +version: '3.9'
Потом просто директорию удалить

2024-08-10 15:17 UTC, alexseipopov commented on for_test/docker-compose.yml
> +version: '3.9'
Кринж. Ей луче самой создать. Можешь эти файлы закинуть в матермост, в канал notification-service (приветный)

2024-08-10 15:17 UTC, alexseipopov commented on for_test/docker-compose.yml
> +version: '3.9'
Приватный*

2024-08-11 07:06 UTC, closed without merging